---
apiVersion: v1
kind: Service
metadata:
 name: shop-loadbalancer
 namespace: shop
spec:
 type: LoadBalancer
 ports:
 - port: 80 #порт, на котором службы будет доступна
   targetPort: 8080  #порт контейнера. куда служба будет перенаправлять
 selector:
   app: shop
