---
## Default Elasticsearch configuration from elasticsearch-docker.
## from https://github.com/elastic/elasticsearch-docker/blob/master/.tedi/template/elasticsearch.yml
#
cluster.name: "docker-cluster"
network.host: 0.0.0.0

## Use single node discovery in order to disable production mode and avoid bootstrap checks
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
#
discovery.type: single-node

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
#
xpack.license.self_generated.type: basic
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
#СЕРТИФИКАТЫ
#xpack.security.http.ssl.enabled: true
#xpack.security.http.ssl.key: $CERTS_DIR/es01/es01.key
#xpack.security.http.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
#xpack.security.http.ssl.certificate: $CERTS_DIR/es01/es01.crt
#xpack.security.transport.ssl.enabled: true
#xpack.security.transport.ssl.verification_mode: certificate
#xpack.security.transport.ssl.certificate_authorities: $CERTS_DIR/ca/ca.crt
#xpack.security.transport.ssl.certificate: $CERTS_DIR/es01/es01.crt
#xpack.security.transport.ssl.key: $CERTS_DIR/es01/es01.key
