version: '3.8'

services:
  grafana:
    hostname: 'grafana'
    image: grafana/grafana
    environment:
      - SOMEVAR=somevar
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    ports:
      - "3000:3000"
    user: "472"
    logging:
      options:
        max-size: 100m
    networks:
      backend:
        aliases:
         - grafana
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        # constraints: [node.role == manager]
        # constraints: [node.hostname == {{ host_01 }}]
      # resources:
      #   limits:
          # cpus: '0.50'
        #   memory: 512m
        # reservations:
          # cpus: '0.50'
          # memory: 512m

networks:
  backend:
    external: true
    name: backend

volumes:
    grafana_data: {}
