version: '3.8'

services:
  prometheus:
    hostname: 'prometheus'
    image: prom/prometheus
    environment:
      - SOMEVAR=somevar
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - "9090:9090"
    logging:
      options:
        max-size: 100m
    networks:
      backend:
        aliases:
         - prometheus
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1
        # constraints: [node.role == manager]
        # constraints: [node.hostname == {{ host_01 }}]
      # resources:
      #   limits:
          # cpus: '0.50'
        #   memory: 512m
        # reservations:
          # cpus: '0.50'
          # memory: 512m

networks:
  backend:
    external: true
    name: backend

volumes:
    prometheus_data: {}
